train-lgb:
		python main.py --train_file ../../dataset/train.csv --test_file ../../dataset/test.csv --result_path ../result/submission_lgb.csv 
train-xgb:
		python main.py --train_file ../../dataset/train.csv --test_file ../../dataset/test.csv --result_path ../result/submission_xgb.csv --model xgb 
mf:
		python matrix_factorization.py --train_file ../../dataset/train.csv --test_file ../../dataset/test.csv --latent_feature_path ../features